### ISSUE TITLE
Traducción Metasploit Framework

### ISSUE THREAD

**Issue by josegatica** [josegatica/parrot-docu-es#1]
https://docs.parrotsec.org/doku.php/metasploit-framework

Para tener en cuenta:
- Referirse al lector como USTED.
- Traducción se hace SOBRE el código fuente de la documentación oficial, por lo que debe descargarse en un archivo .txt

**Comment by danigbaameiro** [comment]
¡Hola!
Voy a encargarme de esta traducción. Soy @dgbame en telegram :D

**Comment by josegatica** [comment]
Genial. Gracias por aportar
