### ISSUE TITLE
Traducción Anonsurf

### ISSUE THREAD

**Issue by josegatica** [josegatica/parrot-docu-es#2]
https://docs.parrotsec.org/doku.php/anonsurf

Para tener en cuenta:
- Referirse al lector como USTED.
- Traducción se hace SOBRE el código fuente de la documentación oficial, por lo que debe descargarse en un archivo .txt

**Comment by selinextapia** [comment]
hola voy a  encargarme de esta  traduccion att :+1:  @anonima publica

**Comment by josegatica** [comment]
impecable :smiley:  gracias por aportar al proyecto
