### ISSUE TITLE
Traducción Compile a Custom Kernel

### ISSUE THREAD

**Issue by josegatica** [josegatica/parrot-docu-es#3]
https://docs.parrotsec.org/doku.php/devel/compile-a-custom-kernel

Para tener en cuenta:
- Referirse al lector como USTED.
- Traducción se hace SOBRE el código fuente de la documentación oficial, por lo que debe descargarse en un archivo .txt

**Comment by YakovMaxim** [comment]
Tomare ésta

Saludos

**Comment by josegatica** [comment]
Genial, gracias por tu aporte al proyecto :smiley:
