### ISSUE TITLE
Traducción Mirrors List

### ISSUE THREAD

**Issue by josegatica** [josegatica/parrot-docu-es#4]
https://docs.parrotsec.org/doku.php/mirrors-list

Para tener en cuenta:
- Referirse al lector como USTED.
- Traducción se hace SOBRE el código fuente de la documentación oficial, por lo que debe descargarse en un archivo .txt

**Comment by alondron** [comment]
Yo voy con esta :)

**Comment by josegatica** [comment]
Perfecto!  Gracias por tu aporte al proyecto
